spring.datasource.url=jdbc:postgresql://localhost:5432/employeemanagement
spring.datasource.username=postgres
spring.datasource.password=Abisha@170203
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
server.port=8088